In [38]:
import numpy as np

In [ ]:
# Excercise 1

In [118]:
a = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

In [117]:
mean_a = a.mean(axis=0)

In [116]:
mean_a

array([2. , 8.4])

In [57]:
# Excercise 2

In [115]:
a_centered = np.subtract(a, mean_a)

In [114]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [64]:
# Excercise 3

In [119]:
a_centered_sp = (a_centered[:,0] @ a_centered[:, 1]) / a.shape[0] - 1

In [120]:
a_centered_sp

0.6000000000000001

In [87]:
# Excercise 4

In [121]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])